/*SQL TRIAL CODE*/

create table DOCTOR(
DOC_LICENSE_NUM  CHAR(7) NOT NULL UNIQUE,
LAST_NAME VARCHAR(20) NOT NULL,
FIRST_NAME VARCHAR(15)  NOT NULL,
ADDRESS VARCHAR(50),
PRIMARY KEY (DOC_LICENSE_NUM)
);

create table PATIENT(
PAT_ID_NUM VARCHAR(15) NOT NULL UNIQUE,
PHY_LICENSE_NUM CHAR(7) NOT NULL,
STAFF_LICENSE_NUM CHAR(7) NOT NULL,
VA_WITH_SPECT_RIGHT VARCHAR(7) NOT NULL,
VA_WITH_SPECT_LEFT VARCHAR(7) NOT NULL,
VA_NO_SPECT_RIGHT VARCHAR(7) NOT NULL,
VA_NO_SPECT_LEFT VARCHAR(7) NOT NULL,
VISUAL_DISABILITY VARCHAR(15),
DISABILITY_CAUSE VARCHAR(30),
RIGHT_EYE_AFFECTED VARCHAR(12),
LEFT_EYE_AFFECTED VARCHAR(12),
PRIMARY KEY (PAT_ID_NUM),
FOREIGN KEY (PHY_LICENSE_NUM) references DOCTOR(DOC_LICENSE_NUM) on update cascade
);

create table SURGERY(
CASE_NUM CHAR(10) NOT NULL UNIQUE,
SURG_LICENSE_NUM CHAR(7) NOT NULL,
PAT_ID_NUM VARCHAR(15) NOT NULL,
VISUAL_IMPARITY VARCHAR(100) NOT NULL,
MED_HISTORY VARCHAR(100),
DIAGNOSIS VARCHAR(100),
CLEARANCE_NUM VARCHAR(10) NOT NULL,
SURG_ADDRESS VARCHAR(50),
SURG_DATE DATE NOT NULL,
REMARKS VARCHAR(100),
PRIMARY KEY (CASE_NUM),
FOREIGN KEY (SURG_LICENSE_NUM) REFERENCES DOCTOR(DOC_LICENSE_NUM) on update cascade,
FOREIGN KEY (PAT_ID_NUM) REFERENCES PATIENT(PAT_ID_NUM) on update cascade
);