	drop database lukedb;
	create database lukedb;
	use lukedb;


	create table patient(
		patient_id int unsigned not null auto_increment primary key,
		patient_fname varchar(30) not null,
		patient_lname varchar(30) not null,
		patient_minitial char(1) not null
	);

	CREATE TABLE STAFF(
		STAFF_LICENSE_NUM CHAR(7) NOT NULL,
		STAFF_FNAME VARCHAR(20) NOT NULL,
		STAFF_LNAME VARCHAR(20) NOT NULL,
		PRIMARY KEY (STAFF_LICENSE_NUM)
	);

	create table DOCTOR(
		DOC_LICENSE_NUM  CHAR(7) NOT NULL UNIQUE,
		LAST_NAME VARCHAR(20) NOT NULL,
		FIRST_NAME VARCHAR(20)  NOT NULL,
		ADDRESS VARCHAR(50),
		SPECIALIZATION VARCHAR(25),
		VISIBLE CHAR(1),
		PRIMARY KEY (DOC_LICENSE_NUM)
	);

	CREATE TABLE `eyepatient` (
  `PAT_ID_NUM` varchar(15) NOT NULL,
  `PAT_UNIV_ID` int(10) UNSIGNED NOT NULL,
  `PAT_FNAME` varchar(20) NOT NULL,
  `PAT_LNAME` varchar(20) NOT NULL,
  `PAT_AGE` varchar(6) NOT NULL,
  `PAT_PH` char(1) NOT NULL,
  `PAT_SEX` char(1) NOT NULL,
  `PHY_LICENSE_NUM` char(7) DEFAULT NULL,
  `STAFF_LICENSE_NUM` char(7) DEFAULT NULL,
  `PRE_VA_WITH_SPECT_LEFT` varchar(7) NOT NULL,
  `POST_VA_WITH_SPECT_LEFT` varchar(7) DEFAULT NULL,
  `PRE_VA_WITH_SPECT_RIGHT` varchar(7) NOT NULL,
  `POST_VA_WITH_SPECT_RIGHT` varchar(7) DEFAULT NULL,
  `PRE_VA_NO_SPECT_LEFT` varchar(7) NOT NULL,
  `POST_VA_NO_SPECT_LEFT` varchar(7) DEFAULT NULL,
  `PRE_VA_NO_SPECT_RIGHT` varchar(7) NOT NULL,
  `POST_VA_NO_SPECT_RIGHT` varchar(7) DEFAULT NULL,
  `VISUAL_DISABILITY` varchar(15) DEFAULT NULL,
  `DISABILITY_CAUSE` varchar(30) DEFAULT NULL,
  `RIGHT_DIAGNOSIS` varchar(30) DEFAULT NULL,
  `LEFT_DIAGNOSIS` varchar(30) DEFAULT NULL
);

CREATE TABLE `surgery` (
  `CASE_NUM` char(10) NOT NULL,
  `SURG_LICENSE_NUM` char(7) NOT NULL,
  `SURG_LICENSE_NUM1` char(7) DEFAULT NULL,
  `SURG_LICENSE_NUM2` char(7) DEFAULT NULL,
  `PAT_ID_NUM` varchar(15) NOT NULL,
  `VISUAL_IMPARITY` varchar(100) NOT NULL,
  `MED_HISTORY` varchar(100) DEFAULT NULL,
  `RIGHT_DIAGNOSIS` varchar(30) DEFAULT NULL,
  `LEFT_DIAGNOSIS` varchar(30) DEFAULT NULL,
  `SURG_ANESTHESIA` varchar(25) NOT NULL,
  `SURG_ADDRESS` varchar(50) NOT NULL,
  `SURG_DATE` date NOT NULL,
  `REMARKS` varchar(100) DEFAULT NULL,
  `INTERNIST` varchar(40) DEFAULT NULL,
  `INTERNIST1` varchar(40) DEFAULT NULL,
  `INTERNIST2` varchar(40) DEFAULT NULL,
  `ANESTHESIOLOGIST` varchar(40) NOT NULL,
  `PROCEDURE_TO_DO` varchar(30) NOT NULL,
  `EYE_OPERATED` varchar(10) NOT NULL,
  `IOLPOWER` varchar(20) NOT NULL,
  `PC_IOL` decimal(8,2) DEFAULT NULL,
  `PC_LAB` decimal(8,2) DEFAULT NULL,
  `PC_PF` decimal(8,2) DEFAULT NULL,
  `SPO_IOL` decimal(8,2) DEFAULT NULL,
  `SPO_OTHERS` decimal(8,2) DEFAULT NULL,
  `CSF_HBILL` decimal(8,2) DEFAULT NULL,
  `CSF_SUPPLIES` decimal(8,2) DEFAULT NULL,
  `CSF_LAB` decimal(8,2) DEFAULT NULL,
  `NDDCH_RA` decimal(8,2) DEFAULT NULL,
  `NDDCH_ZEISS` decimal(8,2) DEFAULT NULL,
  `NDDCH_SUPPLIES` decimal(8,2) DEFAULT NULL,
  `LF_PF` decimal(8,2) DEFAULT NULL,
  `LF_CPC` decimal(8,2) DEFAULT NULL
);
